name: Testes E2E e API — Cypress

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código fonte
        # actions/checkout@v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Configurar Node.js
        # actions/setup-node@v6
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar lint
        run: npm run lint

      - name: Executar testes de API
        # cypress-io/github-action@v7
        uses: cypress-io/github-action@dca986193e4336cb32820819b07e9ecacacaaaf6
        with:
          spec: cypress/e2e/api/**
          install: false
          summary-title: 'Testes de API'
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

      - name: Executar testes E2E Frontend
        # cypress-io/github-action@v7
        uses: cypress-io/github-action@dca986193e4336cb32820819b07e9ecacacaaaf6
        with:
          spec: cypress/e2e/frontend/**
          install: false
          summary-title: 'Testes E2E Frontend'
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

      - name: Salvar screenshots em caso de falha
        # actions/upload-artifact@v7
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Salvar vídeos de execução
        # actions/upload-artifact@v7
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
